name: gnome-2048
adopt-info: gnome-2048
grade: stable
confinement: strict
base: core24

# Launchpad doesn't recognize these fields yet
passthrough:
  license: GPL-3.0+
  title: GNOME 2048

slots:
  # for GtkApplication registration
  gnome-2048:
    interface: dbus
    bus: session
    name: org.gnome.TwentyFortyEight

apps:
  gnome-2048:
    extensions: [gnome]
    command: usr/bin/gnome-2048
    desktop: usr/share/applications/org.gnome.TwentyFortyEight.desktop
    common-id: org.gnome.TwentyFortyEight
    # Disabling Wayland is required while gnome-2048 is based on clutter
    # Probably will be possible to remove it when it is migrated to Gtk4
    environment:
      DISABLE_WAYLAND: 'true'

parts:
  gnome-2048:
    source: https://gitlab.gnome.org/GNOME/gnome-2048.git
    source-type: git
    source-tag: '3.38.2'
    source-depth: 1
# ext:updatesnap
#   version-format:
#     lower-than: '3.39'
#     no-9x-revisions: true
    plugin: meson
    meson-parameters:
      - --prefix=/usr
      - --buildtype=release
    parse-info: [usr/share/metainfo/org.gnome.TwentyFortyEight.appdata.xml]
    override-pull: |
      craftctl default
      craftctl set version=$(git describe --tags --abbrev=10)
      for i in $CRAFT_PROJECT_DIR/patches/*.diff; do
        patch -p1 < $i
      done
      sed -i.bak -e "s|'gnome-2048',|'gnome-2048', symlink_media: false,|g" help/meson.build


  # Find files provided by the base and platform snap and ensure they aren't
  # duplicated in this snap
  cleanup:
    after: [gnome-2048]
    plugin: nil
    build-snaps: [core24, gtk-common-themes, gnome-46-2404]
    override-prime: |
      set -eux
      for snap in "core24" "gtk-common-themes" "gnome-46-2404"; do
        cd "/snap/$snap/current" && find . -type f,l -name *.so.* -exec rm -f "$CRAFT_PRIME/{}" \;
      done
